global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'node'
    static_configs:
      - targets: ['REPLACE_APP_IP:9100']

  - job_name: 'app'
    metrics_path: /metrics
    static_configs:
      - targets: ['REPLACE_APP_IP:8080']
